version: '3.8'

services:
  wordpress:
    build:
      context: .
    container_name: dockpress_wordpress
    ports:
      - "8000:80"
    volumes:
      - ./wp:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: ${PROJECT_NAME}
      WORDPRESS_DB_USER: ${ADMIN_USER}
      WORDPRESS_DB_PASSWORD: ${ADMIN_PASS}
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: dockpress_db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${PROJECT_NAME}
      MYSQL_USER: ${ADMIN_USER}
      MYSQL_PASSWORD: ${ADMIN_PASS}
      MYSQL_ROOT_PASSWORD: root

volumes:
  db_data:
